// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AnalyticsHubListingIAMMemberConditionInitParameters struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type AnalyticsHubListingIAMMemberConditionObservation struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	Title *string `json:"title,omitempty" tf:"title,omitempty"`
}

type AnalyticsHubListingIAMMemberConditionParameters struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	Title *string `json:"title" tf:"title,omitempty"`
}

type AnalyticsHubListingIAMMemberInitParameters struct {
	Condition *AnalyticsHubListingIAMMemberConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	DataExchangeID *string `json:"dataExchangeId,omitempty" tf:"data_exchange_id,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/bigquery/v1beta2.AnalyticsHubListing
	ListingID *string `json:"listingId,omitempty" tf:"listing_id,omitempty"`

	// Reference to a AnalyticsHubListing in bigquery to populate listingId.
	// +kubebuilder:validation:Optional
	ListingIDRef *v1.Reference `json:"listingIdRef,omitempty" tf:"-"`

	// Selector for a AnalyticsHubListing in bigquery to populate listingId.
	// +kubebuilder:validation:Optional
	ListingIDSelector *v1.Selector `json:"listingIdSelector,omitempty" tf:"-"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type AnalyticsHubListingIAMMemberObservation struct {
	Condition *AnalyticsHubListingIAMMemberConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	DataExchangeID *string `json:"dataExchangeId,omitempty" tf:"data_exchange_id,omitempty"`

	Etag *string `json:"etag,omitempty" tf:"etag,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	ListingID *string `json:"listingId,omitempty" tf:"listing_id,omitempty"`

	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type AnalyticsHubListingIAMMemberParameters struct {

	// +kubebuilder:validation:Optional
	Condition *AnalyticsHubListingIAMMemberConditionParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// +kubebuilder:validation:Optional
	DataExchangeID *string `json:"dataExchangeId,omitempty" tf:"data_exchange_id,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-gcp/apis/bigquery/v1beta2.AnalyticsHubListing
	// +kubebuilder:validation:Optional
	ListingID *string `json:"listingId,omitempty" tf:"listing_id,omitempty"`

	// Reference to a AnalyticsHubListing in bigquery to populate listingId.
	// +kubebuilder:validation:Optional
	ListingIDRef *v1.Reference `json:"listingIdRef,omitempty" tf:"-"`

	// Selector for a AnalyticsHubListing in bigquery to populate listingId.
	// +kubebuilder:validation:Optional
	ListingIDSelector *v1.Selector `json:"listingIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	Member *string `json:"member,omitempty" tf:"member,omitempty"`

	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

// AnalyticsHubListingIAMMemberSpec defines the desired state of AnalyticsHubListingIAMMember
type AnalyticsHubListingIAMMemberSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AnalyticsHubListingIAMMemberParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AnalyticsHubListingIAMMemberInitParameters `json:"initProvider,omitempty"`
}

// AnalyticsHubListingIAMMemberStatus defines the observed state of AnalyticsHubListingIAMMember.
type AnalyticsHubListingIAMMemberStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AnalyticsHubListingIAMMemberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AnalyticsHubListingIAMMember is the Schema for the AnalyticsHubListingIAMMembers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,gcp}
type AnalyticsHubListingIAMMember struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataExchangeId) || (has(self.initProvider) && has(self.initProvider.dataExchangeId))",message="spec.forProvider.dataExchangeId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.member) || (has(self.initProvider) && has(self.initProvider.member))",message="spec.forProvider.member is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.role) || (has(self.initProvider) && has(self.initProvider.role))",message="spec.forProvider.role is a required parameter"
	Spec   AnalyticsHubListingIAMMemberSpec   `json:"spec"`
	Status AnalyticsHubListingIAMMemberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AnalyticsHubListingIAMMemberList contains a list of AnalyticsHubListingIAMMembers
type AnalyticsHubListingIAMMemberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AnalyticsHubListingIAMMember `json:"items"`
}

// Repository type metadata.
var (
	AnalyticsHubListingIAMMember_Kind             = "AnalyticsHubListingIAMMember"
	AnalyticsHubListingIAMMember_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AnalyticsHubListingIAMMember_Kind}.String()
	AnalyticsHubListingIAMMember_KindAPIVersion   = AnalyticsHubListingIAMMember_Kind + "." + CRDGroupVersion.String()
	AnalyticsHubListingIAMMember_GroupVersionKind = CRDGroupVersion.WithKind(AnalyticsHubListingIAMMember_Kind)
)

func init() {
	SchemeBuilder.Register(&AnalyticsHubListingIAMMember{}, &AnalyticsHubListingIAMMemberList{})
}
